export enum GameModeEnum {
    START = 'start',
    WORLD = 'world',
    BATTLE = 'battle',
    GET_OUT = 'get-out',
    NEW_CHAPTER = 'new-chapter',
    GAME_OVER = 'game-over',
    GAME_OVER_HOLE = 'game-over-hole',
    GAME_OVER_UNDERWATER = 'game-over-underwater',
    GAME_WON = 'game-won',
    VICTORY_EVIL_QUEEN = 'victory-evil-queen',
    SPELL_BROKEN = 'spell-broken',
    CHAPTER3 = 'chapter3',
    COLLECT_MERMAID_TEAR = 'collect-mermaid-tear',
    GO_TO_MERMAID_CITY = 'go-to-mermaid-city',
    WHIRLPOOL = 'whirlpool',
    VICTORY_SEA_MONSTERS = 'victory-sea-monsters',
    DELIVER_MERMAID_TEAR = 'deliver-mermaid-tear',
    RESTORE_BALANCE = 'restore-balance',
    EXPLOSION = 'explosion',
    BALANCE_RESTORED = 'balance-restored',
    GAME_WON_CHAPTER3_REWARD = 'game-won-chapter3-reward',
}

export const MELTED_PISCESTOWN_GAME_MODES = [
    GameModeEnum.VICTORY_EVIL_QUEEN,
    GameModeEnum.SPELL_BROKEN,
    GameModeEnum.CHAPTER3,
    GameModeEnum.COLLECT_MERMAID_TEAR,
    GameModeEnum.GO_TO_MERMAID_CITY,
    GameModeEnum.WHIRLPOOL,
    GameModeEnum.VICTORY_SEA_MONSTERS,
    GameModeEnum.DELIVER_MERMAID_TEAR,
    GameModeEnum.RESTORE_BALANCE,
    GameModeEnum.EXPLOSION,
    GameModeEnum.BALANCE_RESTORED,
    GameModeEnum.GAME_WON_CHAPTER3_REWARD,
];

export enum DialogActionEnum {
    VICOTRY = 'victory',
    VIDEO = 'video',
    PHOTO = 'photo',
    LETTER = 'letter',
    GO_TO_SKY = 'go-to-sky',
    ENTER_DUNGEON = 'enter-dungeon',
    BATTLE_EVIL_KING = 'battle-evil-king',
    GAME_OVER = 'game-over',
    FOLLOW_HERO = 'follow-hero',
    EXIT_DUNGEON = 'exit-dungeon',
    LEAVE_DUNGEON = 'leave-dungeon',
    GO_TO_GROUND = 'go-to-ground',
    FOLLOW_HERO_HOME = 'follow-hero-home',
    BEFORE_BATTLE_EVIL_QUEEN = 'before-battle-evil-queen',
    BEFORE_BATTLE_EVIL_QUEEN2 = 'before-battle-evil-queen2',
    BATTLE_EVIL_QUEEN = 'battle-evil-queen',
    VICTORY_EVIL_QUEEN = 'victory-evil-queen',
    GAME_OVER_EVIL_QUEEN = 'game-over-evil-queen',
    GAME_WON_EVIL_QUEEN = 'game-won-evil-queen',
    REWARDED_KING = 'rewarded-king',
    RECEIVE_SWORD = 'receive-sword',
    SPELL_BROKEN = 'spell-broken',
    SEER_COMES_OUT = 'seer-comes-out',
    COLLECT_MERMAID_TEAR = 'collect-mermaid-tear',
    RECEIVE_POTION = 'receive-potion',
    GO_TO_MERMAID_CITY = 'go-to-mermaid-city',
    SEA_MONSTER1_BATTLE = 'sea-monster1-battle',
    SEA_MONSTER2_BATTLE = 'sea-monster2-battle',
    VICTORY_SEA_MONSTERS = 'victory-sea-monsters',
    GET_MERMAID_TEAR = 'get-mermaid-tear',
    RECEIVE_MERMAID_TEAR = 'receive-mermaid-tear',
    RESTORE_BALANCE = 'restore-balance',
    BALANCE_RESTORED = 'balance-restored',
    CHAPTER3_REWARD = 'chapter3-reward',
    DEFAULT = '',
}
