import SeaMonster1Fight from '../../images/heroes/seaMonster1_fight.png';
import SeaMonster2Fight from '../../images/heroes/seaMonster2_fight.png';

export const whiteFish = {
    id: 'npc-21',
    x: 4,
    y: 8,
    step: 0,
    dir: 0,
    followHero: false,
    heroClass: 'NPC',
    heroImg: null,
    stopMoving: false,
    type: 'npc',
    map: ['underwater', 'underwater2', 'underwater3'],
    dead: false,
    animate: '',
    npcSummary: {
        main: false,
        name: 'White Fish',
        level: 2,
        health: 24,
        maxHealth: 24,
    },
};
export const blueFish = {
    id: 'npc-22',
    x: 2,
    y: 2,
    step: 0,
    dir: 0,
    followHero: false,
    heroClass: 'NPC',
    heroImg: null,
    stopMoving: false,
    type: 'npc',
    map: ['underwater', 'underwater2', 'underwater3'],
    dead: false,
    animate: '',
    npcSummary: {
        main: false,
        name: 'Blue Fish',
        level: 2,
        health: 24,
        maxHealth: 24,
    },
};
export const greenFish = {
    id: 'npc-23',
    x: 13,
    y: 8,
    step: 0,
    dir: 0,
    followHero: false,
    heroClass: 'NPC',
    heroImg: null,
    stopMoving: false,
    type: 'npc',
    map: ['underwater', 'underwater2', 'underwater3'],
    dead: false,
    animate: '',
    npcSummary: {
        main: false,
        name: 'Green Fish',
        level: 2,
        health: 24,
        maxHealth: 24,
    },
};
export const beigeFish = {
    id: 'npc-24',
    x: 8,
    y: 14,
    step: 0,
    dir: 0,
    followHero: false,
    heroClass: 'NPC',
    heroImg: null,
    stopMoving: false,
    type: 'npc',
    map: ['underwater', 'underwater2', 'underwater3'],
    dead: false,
    animate: '',
    npcSummary: {
        main: false,
        name: 'Beige Fish',
        level: 2,
        health: 24,
        maxHealth: 24,
    },
};
export const redFish = {
    id: 'npc-25',
    x: 13,
    y: 10,
    step: 0,
    dir: 0,
    followHero: false,
    heroClass: 'NPC',
    heroImg: null,
    stopMoving: false,
    type: 'npc',
    map: ['underwater', 'underwater2', 'underwater3'],
    dead: false,
    animate: '',
    npcSummary: {
        main: false,
        name: 'Red Fish',
        level: 2,
        health: 24,
        maxHealth: 24,
    },
};

export const merman1 = {
    id: 'npc-26',
    x: 6,
    y: 14,
    step: 0,
    dir: 0,
    followHero: false,
    heroClass: 'NPC',
    heroImg: null,
    stopMoving: false,
    type: 'npc',
    map: ['underwater'],
    dead: false,
    animate: '',
    npcSummary: {
        main: false,
        name: 'Merman 1',
        level: 2,
        health: 24,
        maxHealth: 24,
    },
};
export const mermaid1 = {
    id: 'npc-27',
    x: 13,
    y: 8,
    step: 0,
    dir: 0,
    followHero: false,
    heroClass: 'NPC',
    heroImg: null,
    stopMoving: false,
    type: 'npc',
    map: ['underwater', 'underwater4'],
    dead: false,
    animate: '',
    npcSummary: {
        main: false,
        name: 'Mermaid 1',
        level: 2,
        health: 24,
        maxHealth: 24,
    },
};
export const merman2 = {
    id: 'npc-28',
    x: 7,
    y: 14,
    step: 0,
    dir: 0,
    followHero: false,
    heroClass: 'NPC',
    heroImg: null,
    stopMoving: false,
    type: 'npc',
    map: ['underwater2', 'underwater4'],
    dead: false,
    animate: '',
    npcSummary: {
        main: false,
        name: 'Merman 2',
        level: 2,
        health: 24,
        maxHealth: 24,
    },
};
export const mermaid2 = {
    id: 'npc-29',
    x: 2,
    y: 8,
    step: 0,
    dir: 0,
    followHero: false,
    heroClass: 'NPC',
    heroImg: null,
    stopMoving: false,
    type: 'npc',
    map: ['underwater', 'underwater4'],
    dead: false,
    animate: '',
    npcSummary: {
        main: false,
        name: 'Mermaid 2',
        level: 2,
        health: 24,
        maxHealth: 24,
    },
};
export const mermaidQueen = {
    id: 'npc-30',
    x: 8,
    y: 8,
    step: 0,
    dir: 0,
    followHero: false,
    heroClass: 'NPC',
    heroImg: null,
    stopMoving: false,
    type: 'npc',
    map: ['underwater4'],
    dead: false,
    animate: '',
    npcSummary: {
        main: false,
        name: 'Mermaid Queen',
        level: 2,
        health: 24,
        maxHealth: 24,
    },
};

export const seaMonster1 = {
    id: 'npc-31',
    x: 9,
    y: 9,
    step: 0,
    dir: 1,
    followHero: false,
    heroClass: 'PUREEVIL',
    heroImg: null,
    stopMoving: true,
    type: 'npc',
    map: ['underwater4'],
    dead: false,
    animate: '',
    npcSummary: {
        main: false,
        name: 'Sea Monster 1',
        img: SeaMonster1Fight,
        level: 20,
        health: 655,
        maxHealth: 655,
        magic: 80,
        attack: 100,
        defense: 70,
        magicDefense: 50,
    },
};
export const seaMonster2 = {
    id: 'npc-32',
    x: 10,
    y: 8,
    step: 0,
    dir: 1,
    followHero: false,
    heroClass: 'PUREEVIL',
    heroImg: null,
    stopMoving: true,
    type: 'npc',
    map: ['underwater4'],
    dead: false,
    animate: '',
    npcSummary: {
        main: false,
        name: 'Sea Monster 2',
        img: SeaMonster2Fight,
        level: 20,
        health: 655,
        maxHealth: 655,
        magic: 100,
        attack: 80,
        defense: 60,
        magicDefense: 70,
    },
};
