import EvilQueenFight from '../../../../images/heroes/evil-queen_fight.png';

export const princessPriska = {
    id: 'npc-2',
    x: 3,
    y: 13,
    step: 0,
    dir: 0,
    followHero: false,
    heroClass: 'PRINCESS',
    heroImg: null,
    stopMoving: true,
    type: 'npc',
    map: ['evilKing'],
    dead: false,
    animate: '',
    npcSummary: {
        main: false,
        name: 'Pri',
        level: 2,
        health: 24,
        maxHealth: 244,
    },
};

export const evilQueen = {
    id: 'npc-3',
    x: 0,
    y: 0,
    step: 0,
    dir: 1,
    followHero: false,
    heroClass: 'PUREEVIL',
    heroImg: null,
    stopMoving: true,
    type: 'npc',
    map: ['piscesTown3'],
    dead: false,
    animate: '',
    npcSummary: {
        main: false,
        name: 'Evil Queen',
        img: EvilQueenFight,
        level: 15,
        health: 455,
        maxHealth: 455,
        magic: 80,
        attack: 65,
        defense: 40,
        magicDefense: 40,
    },
};
export const king = {
    id: 'npc-4',
    x: 0,
    y: 0,
    step: 0,
    dir: 2,
    followHero: false,
    heroClass: 'KING',
    heroImg: null,
    stopMoving: true,
    type: 'npc',
    map: ['piscesTown3'],
    dead: false,
    animate: '',
    npcSummary: {
        main: false,
        name: 'PiscesTown King',
        level: 2,
        health: 24,
        maxHealth: 244,
    },
};

export const servant1 = {
    id: 'npc-5',
    x: 0,
    y: 0,
    step: 0,
    dir: 0,
    followHero: false,
    heroClass: 'NPC',
    heroImg: null,
    stopMoving: true,
    type: 'npc',
    map: ['piscesTown3Melted'],
    dead: false,
    animate: '',
    npcSummary: {
        main: false,
        name: 'Servant 1',
        level: 2,
        health: 24,
        maxHealth: 244,
    },
};

export const servant2 = {
    id: 'npc-6',
    x: 0,
    y: 0,
    step: 0,
    dir: 0,
    followHero: false,
    heroClass: 'NPC',
    heroImg: null,
    stopMoving: true,
    type: 'npc',
    map: ['piscesTown3Melted'],
    dead: false,
    animate: '',
    npcSummary: {
        main: false,
        name: 'Servant 2',
        level: 2,
        health: 24,
        maxHealth: 244,
    },
};

export const ancientSeer = {
    id: 'npc-10',
    x: 0,
    y: 0,
    step: 0,
    dir: 0,
    followHero: false,
    heroClass: 'NPC',
    heroImg: null,
    stopMoving: true,
    type: 'npc',
    map: [],
    dead: false,
    animate: '',
    npcSummary: {
        main: false,
        name: 'Ancient Seer',
        level: 2,
        health: 24,
        maxHealth: 244,
    },
};

export const citizen1 = {
    id: 'npc-11',
    x: 1,
    y: 8,
    step: 0,
    dir: 0,
    followHero: false,
    heroClass: 'NPC',
    heroImg: null,
    stopMoving: false,
    type: 'npc',
    map: ['piscesTownMelted'],
    dead: false,
    animate: '',
    npcSummary: {
        main: false,
        name: 'Citizen 1',
        level: 2,
        health: 24,
        maxHealth: 244,
    },
};
export const citizen2 = {
    id: 'npc-12',
    x: 5,
    y: 7,
    step: 0,
    dir: 0,
    followHero: false,
    heroClass: 'NPC',
    heroImg: null,
    stopMoving: false,
    type: 'npc',
    map: ['piscesTownMelted'],
    dead: false,
    animate: '',
    npcSummary: {
        main: false,
        name: 'Citizen 2',
        level: 2,
        health: 24,
        maxHealth: 244,
    },
};
export const citizen3 = {
    id: 'npc-13',
    x: 7,
    y: 4,
    step: 0,
    dir: 0,
    followHero: false,
    heroClass: 'NPC',
    heroImg: null,
    stopMoving: false,
    type: 'npc',
    map: ['piscesTownMelted'],
    dead: false,
    animate: '',
    npcSummary: {
        main: false,
        name: 'Citizen 3',
        level: 2,
        health: 24,
        maxHealth: 244,
    },
};
export const citizen4 = {
    id: 'npc-14',
    x: 10,
    y: 5,
    step: 0,
    dir: 0,
    followHero: false,
    heroClass: 'NPC',
    heroImg: null,
    stopMoving: false,
    type: 'npc',
    map: ['piscesTownMelted'],
    dead: false,
    animate: '',
    npcSummary: {
        main: false,
        name: 'Citizen 4',
        level: 2,
        health: 24,
        maxHealth: 244,
    },
};
export const citizen5 = {
    id: 'npc-15',
    x: 13,
    y: 8,
    step: 0,
    dir: 0,
    followHero: false,
    heroClass: 'NPC',
    heroImg: null,
    stopMoving: false,
    type: 'npc',
    map: ['piscesTownMelted'],
    dead: false,
    animate: '',
    npcSummary: {
        main: false,
        name: 'Citizen 5',
        level: 2,
        health: 24,
        maxHealth: 244,
    },
};

export const citizen6 = {
    id: 'npc-16',
    x: 13,
    y: 8,
    step: 0,
    dir: 0,
    followHero: false,
    heroClass: 'NPC',
    heroImg: null,
    stopMoving: false,
    type: 'npc',
    map: ['piscesTown2Melted'],
    dead: false,
    animate: '',
    npcSummary: {
        main: false,
        name: 'Citizen 6',
        level: 2,
        health: 24,
        maxHealth: 244,
    },
};

export const citizen7 = {
    id: 'npc-17',
    x: 13,
    y: 8,
    step: 0,
    dir: 0,
    followHero: false,
    heroClass: 'NPC',
    heroImg: null,
    stopMoving: false,
    type: 'npc',
    map: ['piscesTown2Melted'],
    dead: false,
    animate: '',
    npcSummary: {
        main: false,
        name: 'Citizen 7',
        level: 2,
        health: 24,
        maxHealth: 244,
    },
};

export const citizen8 = {
    id: 'npc-18',
    x: 13,
    y: 8,
    step: 0,
    dir: 0,
    followHero: false,
    heroClass: 'NPC',
    heroImg: null,
    stopMoving: false,
    type: 'npc',
    map: ['piscesTown2Melted'],
    dead: false,
    animate: '',
    npcSummary: {
        main: false,
        name: 'Citizen 8',
        level: 2,
        health: 24,
        maxHealth: 244,
    },
};

export const citizen9 = {
    id: 'npc-19',
    x: 13,
    y: 8,
    step: 0,
    dir: 0,
    followHero: false,
    heroClass: 'NPC',
    heroImg: null,
    stopMoving: false,
    type: 'npc',
    map: ['piscesTown2Melted'],
    dead: false,
    animate: '',
    npcSummary: {
        main: false,
        name: 'Citizen 9',
        level: 2,
        health: 24,
        maxHealth: 244,
    },
};

export const citizen10 = {
    id: 'npc-20',
    x: 13,
    y: 8,
    step: 0,
    dir: 0,
    followHero: false,
    heroClass: 'NPC',
    heroImg: null,
    stopMoving: false,
    type: 'npc',
    map: ['house2'],
    dead: false,
    animate: '',
    npcSummary: {
        main: false,
        name: 'Citizen 10',
        level: 2,
        health: 24,
        maxHealth: 244,
    },
};
